---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fork-democracy-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: fork-democracy-secret
    creationPolicy: Owner
  data:
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: fork-democracy
        property: telegram_bot_token
    - secretKey: TELEGRAM_WEBHOOK_SECRET_TOKEN
      remoteRef:
        key: fork-democracy
        property: telegram_webhook_secret_token
    - secretKey: identities.yaml
      remoteRef:
        key: fork-democracy
        property: identities_yaml
