---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fork-democracy
spec:
  interval: 5m
  url: https://github.com/D-o-c-labs/fork_democracy.git
  ref:
    branch: main
