CREATE TABLE IF NOT EXISTS public.soul (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL UNIQUE,
  content text NOT NULL,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.agents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL UNIQUE,
  content text NOT NULL,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.conversations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL,
  user_id text,
  role text NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.memory_daily (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date DEFAULT CURRENT_DATE,
  content text NOT NULL,
  role text DEFAULT 'assistant',
  user_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.memory_long (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text NOT NULL,
  category text DEFAULT 'general',
  importance integer DEFAULT 5 CHECK (importance >= 1 AND importance <= 10),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.mcp_registry (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_name text NOT NULL,
  path text NOT NULL UNIQUE,
  mcp_url text NOT NULL,
  description text,
  tools text[] DEFAULT ARRAY[]::text[],
  workflow_id text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_profiles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL UNIQUE,
  name text,
  display_name text,
  timezone text DEFAULT 'UTC',
  preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  context text,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pending_confirmations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id text NOT NULL,
  requester_user_id text NOT NULL,
  summary text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending',
  confirmation_kind text NOT NULL DEFAULT 'wekan',
  created_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  expires_at timestamp with time zone
);

CREATE INDEX IF NOT EXISTS conversations_session_created_idx
  ON public.conversations (session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS memory_daily_user_date_idx
  ON public.memory_daily (user_id, date DESC);

CREATE INDEX IF NOT EXISTS memory_long_category_idx
  ON public.memory_long (category, created_at DESC);

CREATE INDEX IF NOT EXISTS memory_long_expires_idx
  ON public.memory_long (expires_at);

CREATE INDEX IF NOT EXISTS pending_confirmations_lookup_idx
  ON public.pending_confirmations (chat_id, requester_user_id, status, created_at DESC);
