---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: splitpro-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: splitpro-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTH_SECRET: "{{ .split_pro_auth_secret }}"
        OIDC_ISSUER_URL: "{{ .authentik_split_pro_issuer_url }}"
        OIDC_CLIENT_ID: "{{ .authentik_split_pro_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .authentik_split_pro_client_secret }}"
        OIDC_SCOPES: "openid profile email"
  dataFrom:
    - extract:
        key: splitpro
      rewrite:
        - regexp:
            source: "(.*)"
            target: "split_pro_$1"
    - extract:
        key: authentik
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authentik_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: splitpro-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: splitpro-db-secret
    template:
      type: Opaque
      data:
        # yamllint disable rule:quoted-strings
        DATABASE_URL: '{{ index . "pgbouncer-uri" }}'
        # yamllint enable rule:quoted-strings
  dataFrom:
    - extract:
        key: postgres-pguser-splitpro
