---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
spec:
  interval: 30m
  chart:
    spec:
      chart: ceph-csi-drivers
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: ceph-csi-operator
      interval: 30m
  driftDetection:
    mode: enabled
  values:
    operatorConfig:
      namespace: rook-ceph
      driverSpecDefaults:
        imageSet:
          name: rook-csi-operator-image-set-configmap
        nodePlugin:
          priorityClassName: system-node-critical
        controllerPlugin:
          hostNetwork: true
          priorityClassName: system-cluster-critical
          replicas: 2
    drivers:
      rbd:
        enabled: true
        name: rook-ceph.rbd.csi.ceph.com
        controllerPlugin:
          hostNetwork: true
          replicas: 2
      cephfs:
        enabled: true
        name: rook-ceph.cephfs.csi.ceph.com
        snapshotPolicy: none
        kernelMountOptions:
          ms_mode: prefer-crc
        controllerPlugin:
          hostNetwork: true
          replicas: 2
      nfs:
        enabled: false
        name: rook-ceph.nfs.csi.ceph.com
      nvmeof:
        enabled: false
        name: rook-ceph.nvmeof.csi.ceph.com
