---
name: Schedule - Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: false
        required: false
        type: boolean
      autodiscover_filter:
        description: "Autodiscover filter"
        default: "*"
        required: false
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 * * * *"

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.DOC_APP_ID }}
          private-key: ${{ secrets.DOC_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Renovate
        uses: renovatebot/github-action@22e0a16091fc706b04affe6ae53d5e3358ac4023 # v46.1.19
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
          RENOVATE_DRY_RUN: ${{ inputs.dryRun == true }}
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: ${{ github.repository_owner }}/${{ inputs.autodiscover_filter || '*' }}
          RENOVATE_PLATFORM: "github"
          RENOVATE_PLATFORM_COMMIT: "true"
          RENOVATE_ALLOWED_COMMANDS: "[\"^scripts/renovate/ensure-next-minor\\\\.sh kubernetes/apps/system-upgrade/system-upgrade-controller/ks\\\\.yaml$\"]"
        with:
          token: "${{ steps.app-token.outputs.token }}"
